food/food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views
admin.site.site_header = 'Foodee Admin'
urlpatterns = [
   path('base/',views.BASE,name='base'),
   path('', views.index, name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/myapp/models.py
from django.db import models

# Create your models here.

class Header(models.Model):
    Title = models.CharField(max_length=50)
    Author_Name = models.CharField(max_length=50)
    Link = models.URLField(blank=True, null=True)

    class Meta:
        verbose_name = "Header"
        verbose_name_plural = "Header"

    def __str__(self):
        return self.Title

class About_Us(models.Model):
    Firstcharacter = models.CharField(max_length=1, null=False)
    Paragraph = models.CharField(max_length=1000)
    Get_in_touch = models.URLField(blank=True, null=True)

    class Meta:
        verbose_name = "About Us"
        verbose_name_plural = "About Us"

class Quote(models.Model):
    Quote = models.CharField(max_length=300)
    Quote_author = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Quote"
        verbose_name_plural = "Quote"

    def __str__(self):
        return self.Quote_author

class Food_type(models.Model):
    Food_image = models.ImageField(upload_to='image/Food_type')
    Food_title = models.CharField(max_length=100)
    Food_description = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Food Type"
        verbose_name_plural = "Food Type"

    def __str__(self):
        return self.Food_title

class Food_bg(models.Model):
    Food_Background = models.ImageField(upload_to='image/Food_Background')

    class Meta:
        verbose_name = "Food Background"
        verbose_name_plural = "Food Background"

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = "Food Category"
        verbose_name_plural = "Food Category"

    def __str__(self):
        return self.name

class Food_item(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/', blank=True, null=True)

    class Meta:
        verbose_name = "Food Item"
        verbose_name_plural = "Food Item"

    def __str__(self):
        return self.name

class Event(models.Model):
    Event_title = models.CharField(max_length=200)
    Event_date = models.DateField()
    Event_description = models.TextField()
    Event_link = models.URLField(blank=True, null=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Event"

    def __str__(self):
        return self.Event_title


class Reservation(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    occation = models.CharField(max_length=255)
    date = models.DateField()  # Change to DateField to store in YYYY-MM-DD format
    time = models.CharField(max_length=7)  # Storing time as "HHMM AM/PM"
    message = models.TextField(default='Please Call Back')

    class Meta:
        verbose_name = "Reservation"
        verbose_name_plural = "Reservation"

    def __str__(self):
        return f"Reservation for {self.name} on {self.date}"

class Slide(models.Model):
    image = models.ImageField(upload_to='slides/')
    description = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.description or f'Slide {self.pk}'

food/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Slide, Header,About_Us, Quote,Food_bg, Food_type,Category,Food_item,Event,Reservation
#from .forms import ReservationForm
def BASE(request):
   return render(request,'base.html')

def index(request):
   slides = Slide.objects.all()
   header = Header.objects.first()
   about = About_Us.objects.first()
   quote = Quote.objects.all()
   Fb = Food_bg.objects.first()
   food_type = Food_type.objects.all()
   categories = Category.objects.all()
   food_items = Food_item.objects.all()
   event= Event.objects.all()

   context = {'slides': slides,
              'header': header,
              'about': about,
              'quote': quote,
              'Fb': Fb,
              'food_type': food_type,
              'categories': categories,
              'food_items': food_items,
              'event': event
              }
   if request.method == "POST":
       name = request.POST.get('name')
       email = request.POST.get('email')
       occation = request.POST.get('occation')
       day = request.POST.get('day')
       month = request.POST.get('month')
       year = request.POST.get('year')
       time = request.POST.get('time')
       am_pm = request.POST.get('am_pm')
       message = request.POST.get('message')

       # Combine day, month, and year into a single date
       date = f"{year}-{month.zfill(2)}-{day.zfill(2)}"

       # Handle time formatting if needed
       time_formatted = f"{time.zfill(4)} {am_pm}"

       # Save to database
       reservation = Reservation(
           name=name,
           email=email,
           occation=occation,
           date=date,
           time=time_formatted,
           message=message
       )
       reservation.save()


   return render(request, 'index.html',context)

food/myapp/templates/base.html
{% include 'header.html' %}
<!DOCTYPE html>
{% load static %}
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Foodee &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />


  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic,700italic|Merriweather:300,400italic,300italic,400,700italic' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Simple Line Icons -->
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
	<!-- Datetimepicker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
	<!-- Flexslider -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
    {% block content %}

{% endblock %}
    
    {% include 'footer.html' %}
 	<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
	<!-- Include Flatpickr JS -->
	<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Bootstrap DateTimePicker -->
	<script src="{% static 'js/moment.js' %}"></script>
	<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>

	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<script>
		$(function () {
	       $('#date').datetimepicker();
	   });
	</script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

food/myapp/templates/footer.html
<div id="fh5co-footer">
		<div class="container">
			<div class="row row-padded">
				<div class="col-md-12 text-center">
					<p class="to-animate">&copy; 2016 Foodee Free HTML5 Template. <br> Designed by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Demo Images: <a href="http://pexels.com/" target="_blank">Pexels</a> <br> Tasty Icons Free <a href="http://handdrawngoods.com/store/tasty-icons-free-food-icons/" target="_blank">handdrawngoods</a>
					</p>
					<p class="text-center to-animate"><a href="#" class="js-gotop">Go To Top</a></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="fh5co-social">
						<li class="to-animate-2"><a href="#"><i class="icon-facebook"></i></a></li>
						<li class="to-animate-2"><a href="#"><i class="icon-twitter"></i></a></li>
						<li class="to-animate-2"><a href="#"><i class="icon-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

food/myapp/templates/header.html
<!DOCTYPE html>
{% load static %}
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Foodee &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />


  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">

	<link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic,700italic|Merriweather:300,400italic,300italic,400,700italic' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Simple Line Icons -->
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
	<!-- Datetimepicker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
	<!-- Flexslider -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<div id="fh5co-container">
		<div id="fh5co-home" class="js-fullheight" data-section="home">

			<div class="flexslider">

				<div class="fh5co-overlay"></div>
				<div class="fh5co-text">
					<div class="container">
						<div class="row">
							<h1 class="to-animate">{{header.Title}}</h1>
<br>
							<h2 class="to-animate">Lovely Designed <span>Backend by</span> <a href="{{header.Link}}" target="_blank">{{header.Author_Name}}</a></h2>
						</div>
					</div>
				</div>
			  	<div class="slideshow">
        <ul class="slides">
            {% for slide in slides %}
                <li style="background-image: url({{ slide.image.url }});" data-stellar-background-ratio="0.5">
                    <p>{{ slide.description }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

			</div>

		</div>
		<div class="js-sticky">
			<div class="fh5co-main-nav">
				<div class="container-fluid">
					<div class="fh5co-menu-1">
						<a href="#" data-nav-section="home">Home</a>
						<a href="#" data-nav-section="about">About</a>
						<a href="#" data-nav-section="features">Features</a>
					</div>
					<div class="fh5co-logo">
						<a href="index.html">foodee</a>
					</div>
					<div class="fh5co-menu-2">
						<a href="#" data-nav-section="menu">Menu</a>
						<a href="#" data-nav-section="events">Events</a>
						<a href="#" data-nav-section="reservation">Reservation</a>
					</div>
				</div>

			</div>
		</div>

food/myapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block content %}
		<div id="fh5co-about" data-section="about">
			<div class="fh5co-2col fh5co-bg to-animate-2" style="background-image: url({% static 'images/res_img_1.jpg' %})"></div>
			<div class="fh5co-2col fh5co-text">
				<h2 class="heading to-animate">About Us</h2>
				<p class="to-animate"><span class="firstcharacter">{{about.Firstcharacter}}</span>{{about.Paragraph}}</p>
				<p class="text-center to-animate"><a href="{{Get_in_touch}}" class="btn btn-primary btn-outline">Get in touch</a></p>
			</div>
		</div>

		<div id="fh5co-sayings">
			<div class="container">
				<div class="row to-animate">

					<div class="flexslider">
						<ul class="slides">
								{% for i in quote %}
							<li>
								<blockquote>
									<p>&ldquo; {{i.Quote}}  &rdquo;</p>
									<p class="quote-author">&mdash; {{i.Quote_author}}</p>
								</blockquote>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div id="fh5co-featured" data-section="features">
			<div class="container">
				<div class="row text-center fh5co-heading row-padded">
					<div class="col-md-8 col-md-offset-2">
						<h2 class="heading to-animate">Featured Dishes</h2>
						<p class="sub-heading to-animate">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div>
				</div>
				<div class="row">
					<div class="fh5co-grid">
						<div class="fh5co-v-half to-animate-2">
							<div class="fh5co-v-col-2 fh5co-bg-img" style="background-image: url({% static 'images/res_img_1.jpg' %})"></div>
							<div class="fh5co-v-col-2 fh5co-text fh5co-special-1 arrow-left">
								<h2>Fresh Mushrooms</h2>
								<span class="pricing">$7.50</span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
							</div>
						</div>
						<div class="fh5co-v-half">
							<div class="fh5co-h-row-2 to-animate-2">
								<div class="fh5co-v-col-2 fh5co-bg-img" style="background-image: url({% static 'images/res_img_2.jpg' %})"></div>
								<div class="fh5co-v-col-2 fh5co-text arrow-left">
									<h2>Grilled Chiken Salad</h2>
									<span class="pricing">$12.00</span>
									<p>Far far away, behind the word mountains.</p>
								</div>
							</div>
							<div class="fh5co-h-row-2 fh5co-reversed to-animate-2">
								<div class="fh5co-v-col-2 fh5co-bg-img" style="background-image: url({% static 'images/res_img_8.jpg' %})"></div>
								<div class="fh5co-v-col-2 fh5co-text arrow-right">
									<h2>Cheese and Garlic Toast</h2>
									<span class="pricing">$4.50</span>
									<p>Far far away, behind the word mountains.</p>
								</div>
							</div>
						</div>

						<div class="fh5co-v-half">
							<div class="fh5co-h-row-2 fh5co-reversed to-animate-2">
								<div class="fh5co-v-col-2 fh5co-bg-img" style="background-image: url({% static 'images/res_img_7.jpg' %})"></div>
								<div class="fh5co-v-col-2 fh5co-text arrow-right">
									<h2>Organic Egg</h2>
									<span class="pricing">$4.99</span>
									<p>Far far away, behind the word mountains.</p>
								</div>
							</div>
							<div class="fh5co-h-row-2 to-animate-2">
								<div class="fh5co-v-col-2 fh5co-bg-img" style="background-image: url({% static 'images/res_img_6.jpg' %})"></div>
								<div class="fh5co-v-col-2 fh5co-text arrow-left">
									<h2>Salad with Crispy Chicken</h2>
									<span class="pricing">$8.50</span>
									<p>Far far away, behind the word mountains.</p>
								</div>
							</div>
						</div>
						<div class="fh5co-v-half to-animate-2">
							<div class="fh5co-v-col-2 fh5co-bg-img" style="background-image: url({% static 'images/res_img_3.jpg' %})"></div>
							<div class="fh5co-v-col-2 fh5co-text fh5co-special-1 arrow-left">
								<h2>Tomato Soup with Chicken</h2>
								<span class="pricing">$12.99</span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
							</div>
						</div>

					</div>
				</div>

			</div>
		</div>

		<div id="fh5co-type" style="background-image: url({{Fb.Food_Background}});" data-stellar-background-ratio="0.5">
			<div class="fh5co-overlay"></div>
			<div class="container">
				<div class="row">

						{% for i in food_type %}
					<div class="col-md-3 to-animate">
						<div class="fh5co-type">
							<h3 class="with-icon icon-{{i.id}}">{{i.Food_title}}</h3>
							<p>{{i.Food_description}} </p>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>

		<div id="fh5co-menus" data-section="menu">
    <div class="container">
        <div class="row text-center fh5co-heading row-padded">
            <div class="col-md-8 col-md-offset-2">
                <h2 class="heading to-animate">Food Menu</h2>
                <p class="sub-heading to-animate">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
            </div>
        </div>

        <div class="row row-padded">
            {% for category in categories %}
                <div class="col-md-6">
                    <div class="fh5co-food-menu to-animate-2">
                        <h2 class="fh5co-{{ category.name|slugify }}">{{ category.name }}</h2>
                        <ul>
                            {% for item in food_items %}
                                {% if item.category.id == category.id %}
                                    <li>
                                        <div class="fh5co-food-desc">
                                            <figure>
                                                <img src="{{ item.image.url }}" class="img-responsive" alt="{{ item.name }}">
                                            </figure>
                                            <div>
                                                <h3>{{ item.name }}</h3>
                                                <p>{{ item.description|truncatechars:80 }}</p>
                                            </div>
                                        </div>
                                        <div class="fh5co-food-pricing">
                                            ₹{{ item.price }}
                                        </div>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center to-animate-2">
                <p><a href="#" class="btn btn-primary btn-outline">More Food Menu</a></p>
            </div>
        </div>
    </div>
</div>


		<div id="fh5co-events" data-section="events" style="background-image: url({% static 'images/slide_2.jpg' %});" data-stellar-background-ratio="0.5">
			<div class="fh5co-overlay"></div>
			<div class="container">
				<div class="row text-center fh5co-heading row-padded">
					<div class="col-md-8 col-md-offset-2 to-animate">
						<h2 class="heading">Upcoming Events</h2>
						<p class="sub-heading">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div>
				</div>
				<div class="row">
					{% for i in event %}
					<div class="col-md-4">
						<div class="fh5co-event to-animate-2">
							<h3>{{i.Event_title}}</h3>
							<span class="fh5co-event-meta">{{i.Event_date}}</span>
							<p> {{i.Event_description}}</p>
							<p><a href="{{i.Event_link}}" class="btn btn-primary btn-outline">Read More</a></p>
						</div>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>

		<div id="fh5co-contact" data-section="reservation">
			<div class="container">
				<div class="row text-center fh5co-heading row-padded">
					<div class="col-md-8 col-md-offset-2">
						<h2 class="heading to-animate">Reserve a Table</h2>
						<p class="sub-heading to-animate">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 to-animate-2">
						<h3>Contact Info</h3>
						<ul class="fh5co-contact-info">
							<li class="fh5co-contact-address ">
								<i class="icon-home"></i>
								5555 Love Paradise 56 New Clity 5655, <br>Excel Tower United Kingdom
							</li>
							<li><i class="icon-phone"></i> (123) 465-6789</li>
							<li><i class="icon-envelope"></i>info@freehtml5.co</li>
							<li><i class="icon-globe"></i> <a href="http://freehtml5.co/" target="_blank">freehtml5.co</a></li>
						</ul>
					</div>
					<div class="col-md-6 to-animate-2">
    <h3>Reservation Form</h3>
    <form method="post" action="#">
        {% csrf_token %}
        <div class="form-group">
            <label for="name" class="sr-only">Name</label>
            <input id="name" class="form-control" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="form-group">
            <label for="email" class="sr-only">Email</label>
            <input id="email" class="form-control" name="email" placeholder="Email" type="email" required>
        </div>
        <div class="form-group">
            <label for="occation" class="sr-only">Occasion</label>
            <select class="form-control" id="occation" name="occation">
                <option value="">Select an Occasion</option>
                <option value="Wedding Ceremony">Wedding Ceremony</option>
                <option value="Birthday">Birthday</option>
                <option value="Others">Others</option>
            </select>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="day" class="sr-only">Day</label>
                <select class="form-control" id="day" name="day" required>
                    <option value="">Day</option>
                    {% for i in 1|range_filter:32 %}
                        <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4">
                <label for="month" class="sr-only">Month</label>
                <select class="form-control" id="month" name="month" required>
                    <option value="">Month</option>
                    {% for i in 1|range_filter:13 %}
                        <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4">
                <label for="year" class="sr-only">Year</label>
                <select class="form-control" id="year" name="year" required>
                    <option value="">Year</option>
                    {% for i in 2023|range_filter:2101 %}
                        <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="time" class="sr-only">Time</label>
                <input id="time" class="form-control" name="time" placeholder="Time" type="number" min="0000" max="1159" required>
            </div>
            <div class="form-group col-md-6">
                <label for="am_pm" class="sr-only">AM/PM</label>
                <select id="am_pm" class="form-control" name="am_pm">
                    <option value="AM">AM</option>
                    <option value="PM">PM</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="message" class="sr-only">Message</label>
            <textarea id="message" name="message" cols="30" rows="5" class="form-control" placeholder="Message"></textarea>
        </div>
        <div class="form-group">
            <input class="btn btn-primary" value="Send Message" type="submit">
        </div>
    </form>
</div>





				</div>
			</div>
		</div>


	</div>

<!-- Include Flatpickr initialization -->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        flatpickr("#id_date", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",  // Ensure the format matches what Django expects
        });
    });
</script>
{% endblock %}